---
# file: define_users.yaml - define users on elephant nodes.

- name: remove obsolete sudoers
  file:
    path: "/etc/sudoers.d/{{ item.userid }}"
    state: absent
  with_items: "{{ i_deleted_users }}"

- name: remove access to obsolete IDs
  file:
    path: "/home/{{ item.userid }}/.ssh/authorized_keys"
    state: absent
  with_items: "{{ i_deleted_users }}"

- name: Ensure the default groups exists
  group:
    name: "{{ item.group }}"
    gid: "{{ item.gid }}"
    state: present
  with_items: "{{ i_groups }}"

- name: create login IDs and directories
  user:
    name: "{{ item.userid }}"
    uid: "{{ item.uid }}"
    group: "{{ i_groups.0.group }}"
  with_items: "{{ i_users }}"

- name: create user ssh directories
  file:
    path: "/home/{{ item.userid }}/.ssh"
    state: directory
    owner: "{{ item.userid }}"
    group: "{{ i_groups.0.group }}"
    mode: 0700
  with_items: "{{ i_users }}"

- name: insert user ssh keys
  authorized_key:
    user: "{{ item.userid }}"
    state: present
    key: '{{ item.key }}'
  with_items: "{{ i_user_keys }}"
