---
# file: install_configure_phpmyadmin.yaml
#
# Depends on:
#
#   {{ admin_email }}
#   {{ i_external_connection.0.ipv4 }}
#   {{ phpMyAdmin_secret }}

- set_fact:
    install_phpMyAdmin_apache_group: apache
  when:
  - install_phpMyAdmin_apache_group is undefined

- name: update ssl to listen on port 444
  lineinfile:
    path: /etc/httpd/conf.d/ssl.conf
    regexp: '^Listen 444 '
    insertafter: '^Listen 443 https'
    line: 'Listen 444 https'
  when: 
  - local_web is defined
  - local_web == True

- name: install phpMyAdmin packages
  yum:
    name: ['php', 'phpMyAdmin']
    state: latest
  notify:
  - restart httpd

- debug: msg="{{ install_phpMyAdmin_apache_group }}"

- name: ensure correct permissions on configuration directory
  file:
    dest: /etc/phpMyAdmin
    state: directory
    owner: root
    group: "{{ install_phpMyAdmin_apache_group }}"
    mode: 0750

- name: ensure correct permissions on php home directory
  file:
    dest: /var/lib/php
    state: directory
    owner: root
    group: "{{ install_phpMyAdmin_apache_group }}"
    mode: 0755

- name: configure phMyAdmin server
  template:
    src: etc_phpMyAdmin_config.inc.php.j2
    dest: /etc/phpMyAdmin/config.inc.php
    owner: root
    group: "{{ install_phpMyAdmin_apache_group }}"
    mode: 0640
  notify:
  - restart httpd

- set_fact:
    myadmin_vhost: '{{ i_virtualhosts.1.virtualhost }}'
    myadmin_port: 443
    myadmin_ssl_cert: /etc/letsencrypt/live/{{ i_virtualhosts.1.virtualhost }}/fullchain.pem      
    myadmin_ssl_key: /etc/letsencrypt/live/{{ i_virtualhosts.1.virtualhost }}/privkey.pem
  when: (local_web is undefined) or (local_web == False)

- set_fact:
    myadmin_vhost: localhost
    myadmin_port: 444
    myadmin_ssl_cert: /local_ssl/localhost.crt
    myadmin_ssl_key: /local_ssl/localhost.key
  when:
  - local_web is defined
  - local_web == True

- name: update phMyAdmin httpd configuration
  template:
   src: etc_httpd_conf.d_phpMyAdmin.conf.j2
   dest: /etc/httpd/conf.d/phpMyAdmin.conf
  notify:
  - restart httpd

- meta: flush_handlers

