---
# file: install_python_pip.yaml.

- name: get python pip installation module
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /root/Downloads/get-pip.py
    validate_certs: no
    mode: 0400

- name: install python pip
  command: python /root/Downloads/get-pip.py
  args:
    creates: /bin/pip
